### ISSUE TITLE
Error .cgal_url (Github action)

### ISSUE THREAD

**Issue by stla** [ericdunipace/RcppCGAL#10]
Hello Eric,

Previously I had nothing to do, but now when I use a Github action for one of my packages using **RcppCGAL**, the header files are not automatically downloaded. So I added `RcppCGAL::cgal_install()` to the YAML file defining the Github action, but then this generates an error:

```
Error in assets[[which.as]] : 
  attempt to select less than one element in get1index
Calls: <Anonymous> -> .cgal_url
```

Would you have an idea about what happens?

**Comment by stla** [comment]
Now I've tried `library(RcppCGAL); cgal_install('https://github.com/CGAL/cgal/releases', '5.5.2')` but then I get `cgal_pkg_state not found`.

**Comment by stla** [comment]
So now I did the following and it seems to work:

```r
library(RcppCGAL); cgal_pkg_stage <- list2env(list(ASK_INSTALL = FALSE, CLEANED = FALSE, OLD_VERSION = NA_character_, VERSION = NA_character_, WARNED = FALSE)); cgal_install(version = '5.5.2')
```

**Comment by ericdunipace** [comment]
Hi,

It’s due to the release of the 5.6 beta which my function wasn’t able to parse correctly for the download file. I’m testing a version which should handle the beta’s correctly (i.e., download only the last stable release). Should be up later today on GitHub and hopefully on CRAN soon.

Eric

**Comment by ericdunipace** [comment]
The current version on the GitHub here should work. Issue #9 should fix this and is submitted to CRAN. Thanks for flagging!

**Comment by ericdunipace** [comment]
@stla New version on CRAN now and the Github is further updated with some minor wording changes to readme that hopefully makes things more clear in general. Please let me know if you find further bugs!
