### ISSUE TITLE
Upstream CGAL UBSAN issue resulting in CRAN removing package

### ISSUE THREAD

**Issue by tylermorganwall** [ericdunipace/RcppCGAL#15]
raybevel was removed in early march due to an upstream UBSAN issue in CGAL.

https://github.com/CGAL/cgal/issues/5241

This issue resulted in warnings seen in this CRAN output:

https://www.stats.ox.ac.uk/pub/bdr/memtests/clang-UBSAN/raybevel/raybevel-Ex.Rout

The CGAL team has apparently fixed the issue in CGAL 6.0 (planned to be released in June).

**Comment by ericdunipace** [comment]
Thanks for flagging. I'll try to upload a new version of the package with the current master branch of CGAL in the next few days

**Comment by ericdunipace** [comment]
Should hopefully be addressed by the latest release that is on its way to CRAN (#17 )

**Comment by ericdunipace** [comment]
Approved by CRAN; let me know if this fixes the issue.
