### ISSUE TITLE
Current version of CGAL on CRAN has missing member functions, leading to potential package removal

### ISSUE THREAD

**Issue by tylermorganwall** [ericdunipace/RcppCGAL#19]
See the following issue I filed in the CGAL repo for details:

https://github.com/CGAL/cgal/issues/8313

And the failing CRAN logs here:

https://www.stats.ox.ac.uk/pub/bdr/clang19/raybevel.log

**Comment by ericdunipace** [comment]
I reverted to the base version of the CGAL headers (5.6.1) rather than my previous hacky fix for the previous UBSAN issue given another user was having problems with their development version. On reverse dependency checks, `raybevel` passed with the new version and failed to install with the old. Apologies. This should hopefully be resolved.

**Comment by tylermorganwall** [comment]
This is actually a separate issue than the previous UBSAN problem: raybevel currently isn't yet being taken down due to this CGAL header issue, but BDR warned package developers that encountered this issue on llvm/clang19 that the countdown would begin once clang 19 was released. 

Note that I have submitted a pull request (https://github.com/CGAL/cgal/pull/8330) to CGAL that fixes the issue and has been approved and is just waiting to be merged. All you'll have to do (once the PR has been merged) to resolve this is update RcppCGAL's headers to the latest version.

**Comment by ericdunipace** [comment]
Sorry for the misunderstanding!

**Comment by tylermorganwall** [comment]
The pull request has been merged into the [5.6.x-branch](https://github.com/CGAL/cgal/tree/5.6.x-branch):

https://github.com/CGAL/cgal/pull/8330

**Comment by tylermorganwall** [comment]
The latest (6.0) version of CGAL has been released (https://github.com/CGAL/cgal/releases/tag/v6.0) that includes this fix. Can you issue an update to RcppCGAL on the CRAN? Currently, my package raybevel will be removed from the CRAN 10/9/24 unless this is fixed upstream.

**Comment by tylermorganwall** [comment]
Although you might want to wait until 6.0.1, due to the comment referenced here:

https://github.com/CGAL/cgal/pull/8330?notification_referrer_id=NT_kwDOAASKibIxMTM0NjYyMDY2NDoyOTc2MDk&notifications_query=is%3Aunread#issuecomment-2400214817

**Comment by tylermorganwall** [comment]
Note that the CRAN has extended the removal deadline to October 24th, so there's some time.

**Comment by tylermorganwall** [comment]
CGAL 6.0.1 was released yesterday, although not in time for raybevel to be removed. Would you be able to issue an update to RcppCGAL with the latest version?

**Comment by tylermorganwall** [comment]
Any update here? Do you want me to put together a pull request to update RcppCGAL to the latest version?

**Comment by ericdunipace** [comment]
Update @tylermorganwall, I have submitted an update to the package with a breaking change. I tried to have changes made to interpolation but didn't get a reply from the maintainer. From reading around, sometimes CRAN will allow breaking changes to be pushed if efforts were made to provide patches. Will see what they say.

**Comment by tylermorganwall** [comment]
Was there an issue with the submission?

**Comment by tylermorganwall** [comment]
I noticed RcppCGAL wasn't updated or on CRAN incoming--was there any additional issues with the new version?

**Comment by ericdunipace** [comment]
There was another package that `revdepchecks` didn't pick up on my machine. Waiting for their change to push to CRAN or for the recommended 2 weeks to elapse before submitting again. Will keep you updated when RcppCGAL is submitted/approved

**Comment by ericdunipace** [comment]
New RcppCGAL was approved by CRAN. should be there soon
